[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling==1.26.3" ]

[project]
name = "compudoc"
version = "0.13.0"
description = "Add python calculations to your LaTeX, Typst, and Markdown documents."
readme = "README.md"
authors = [
  { name = "CD Clark III", email = "clifton.clark@gmail.com" },
]
requires-python = ">=3.10"

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "art>=6.4",
  "cyclopts>=3.1.2",
  "fspathtree>=1",
  "jinja2>=3.1.4",
  "pyparsing[diagrams]>=3.1.4",
  "typing-extensions>=4.15",
]
scripts."compudoc" = "compudoc.__main__:app"

[dependency-groups]
dev = [
  "black>=24.10",
  "clirunner>=0.1",
  "cram>=0.7",
  "nox>=2024.10.9",
  "pint>=0.24.3",
  "pyerrorprop>=3.1.2",
  "pytest>=8.3.4",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [ "src/compudoc" ]

[tool.uv]
managed = true
