import importlib.metadata
import pathlib
import sys

import cyclopts
import fspathtree
import jinja2
import rich.console
from typing_extensions import Annotated, List

from compudoc import document
from compudoc.execution_engines import *
from compudoc.template_engines import *

console = rich.console.Console(stderr=True)

__version__ = importlib.metadata.version("compudoc")

app = cyclopts.App(name="compudoc", version=__version__)


def detect_filetype(filename):
    filepath = pathlib.Path(filename)
    if filepath.suffix in [".cd", ".compudoc"]:
        filepath = pathlib.Path(filepath.stem)

    filetypes = {
        ".tex": "latex",
        ".md": "markdown",
        ".gnuplot": "gnuplot",
    }
    return filetypes.get(filepath.suffix, None)


comment_line_strs = {
    "latex": "%",
    "markdown": "[comment]: #",
    "gnuplot": "#",
}


@app.default
def main(
    input_file: pathlib.Path,
    output_file: pathlib.Path = None,
    /,
    filetype: str = None,
    strip_comment_blocks: bool = False,
    comment_line_str: str = None,
    python: str = sys.executable,
):
    """
    Compudoc lets you write python code in you documents to perform calculations and insert the results.
    It is very handy for creating technical write-ups that need to record/report the result of some numerical calculations.

    Parameters
    ----------

    output-file
        Output filename template. The output filename will be generated by
        rendering this template. Use --show-output-filename-render-context to see a
        list of variables available in the template.
    filetype
        Set input filetype.
    strip_comment_blocks
        Remove comment blocks from document when rendering.
    comment_line_str
        Specify the string that comment lines will begin with.
    python
        Specify interpreter to use for evaluating code blocks.
    """

    env = jinja2.Environment()
    if output_file is None:
        if input_file.suffix in [".cd", ".compudoc"]:
            output_file = pathlib.Path(input_file.stem)
        else:
            output_file = pathlib.Path(
                input_file.stem + "-rendered" + input_file.suffix
            )

    if filetype is None:
        filetype = detect_filetype(input_file)
    if filetype is None and comment_line_str is None:
        console.print(f"Could not determine filetype for {input_file}")
        return 1

    if filetype == "markdown":
        strip_comment_blocks = True
    if comment_line_str is None:
        comment_line_str = comment_line_strs[filetype]

    console.print(f"Detected filetype: {filetype}")
    console.print(f"Comment string: {comment_line_str}")

    console.print(f"Rendering document {input_file} -> {output_file}")
    input_text = input_file.read_text()

    output_text = document.render_document(
        input_text,
        template_engine=Jinja2(),
        execution_engine=Python(python),
        comment_line_str=comment_line_str,
        strip_comment_blocks=strip_comment_blocks,
    )

    output_file.write_text(output_text)
