import importlib.metadata
import pathlib
import sys

import art
import cyclopts
import fspathtree
import jinja2
import rich.console
from typing_extensions import Annotated, List

from compudoc import document
from compudoc.examples import Examples
from compudoc.execution_engines import *
from compudoc.template_engines import *

__version__ = importlib.metadata.version("compudoc")

app = cyclopts.App(
    name="compudoc",
    version=__version__,
)

supported_filetypes = {
    "latex": {
        "file extensions": [".tex"],
        "comment line strings": ["%"],
        "strip comment blocks": False,
    },
    "markdown": {
        "file extensions": [".md", ".markdown"],
        "comment line strings": ["[comment]: #"],
        "strip comment blocks": True,
    },
    "gnuplot": {
        "file extensions": [".gp", ".gnuplot"],
        "comment line strings": ["#"],
        "strip comment blocks": False,
    },
}


def detect_filetype(filename):
    filepath = pathlib.Path(filename)
    if filepath.suffix in [".cd", ".compudoc"]:
        filepath = pathlib.Path(filepath.stem)

    for ft in supported_filetypes:
        if filepath.suffix in supported_filetypes[ft]["file extensions"]:
            return ft

    return None


@app.default
def main(
    input_file: pathlib.Path,
    output_file: pathlib.Path = None,
    /,
    filetype: str = None,
    strip_comment_blocks: bool = None,
    comment_line_str: str = None,
    python: str = sys.executable,
    quiet: bool = False,
):
    """
    Compudoc lets you write python code in you documents to perform calculations and insert the results.
    It is very handy for creating technical write-ups that need to record/report the result of some numerical calculations.

    Parameters
    ----------

    output-file
        Output filename template. The output filename will be generated by
        rendering this template. Use --show-output-filename-render-context to see a
        list of variables available in the template.
    filetype
        Set input filetype.
    strip_comment_blocks
        Remove comment blocks from document when rendering. Some filetypes do this by default.
    comment_line_str
        Specify the string that comment lines will begin with.
    python
        Specify interpreter to use for evaluating code blocks.
    quiet
        Don't print status info while rendering.
    """

    console = rich.console.Console(stderr=True, quiet=quiet)
    econsole = rich.console.Console(stderr=True, quiet=quiet)
    if output_file is None:
        if input_file.suffix in [".cd", ".compudoc"]:
            output_file = pathlib.Path(input_file.stem)
        else:
            output_file = pathlib.Path(
                input_file.stem + "-rendered" + input_file.suffix
            )

    font = "poinson"
    banner = art.text2art(f"CompuDoc", font=font)
    console.print(banner)
    console.print(f"version: {__version__}\n\n")

    if filetype is None:
        filetype = detect_filetype(input_file)
    if filetype is None and comment_line_str is None:
        console.print(f"Could not determine filetype for {input_file}")
        return 1

    if strip_comment_blocks is None:
        strip_comment_blocks = supported_filetypes[filetype]["strip comment blocks"]
    if comment_line_str is None:
        comment_line_str = supported_filetypes[filetype]["comment line strings"][0]

    console.print(f"Detected filetype: {filetype}")
    console.print(rich.markup.escape(f"Comment string: {comment_line_str}"))

    console.print(f"Rendering document {input_file} -> {output_file}")
    input_text = input_file.read_text()

    doc = document.Document()
    doc.set_comment_block_parser(
        document.CodeBlockParser(comment_line_str=comment_line_str)
    )
    doc.set_template_engine(Jinja2())
    doc.set_execution_engine(Python(python))
    doc.parse(input_text)

    output_text = doc.render(strip_comment_blocks=strip_comment_blocks, quiet=quiet)

    output_file.write_text(output_text)


@app.command
def example(filetype: str = "latex", /):
    """
    Print examples for varous filetypes.

    Parameters
    ==========

    filetype
        The example filtype. Currently supported example filetypes:
            - latex
            - markdown
            - gnuplot
    """

    console = rich.console.Console()
    econsole = rich.console.Console(stderr=True)

    for ft in supported_filetypes:
        identifiers = [ft] + list(
            map(lambda e: e[1:], supported_filetypes[ft]["file extensions"])
        )
        if filetype.lower() in identifiers:
            fn = getattr(Examples, ft)
            print(fn())
            return 0

    econsole.print(f"[red]ERROR: Unrecognized file type '{filetype}'.[/red]")


@app.command
def split(
    input_file: pathlib.Path,
    /,
    filetype: str = None,
    text_suffix: str = ".text",
    code_suffix: str = ".code",
    strip: bool = False,
    comment_line_str: str = None,
    quiet: bool = False,
    overwrite: bool = False,
):
    """
    Split a compudoc into its text and code. This creates two files, one with the document text and one with the document code.
    This is useful for testing/debuggging code blocks.

    Parameters
    ----------

    filetype
        Specify input filetype.
    text_suffix
        Suffix to append to input filename for generating output filename for document text.
    code_suffix
        Suffix to append to input filename for generating output filename for document code.
    strip_all
        Remove _all_ compudoc markdup. By default, only comment code blocks are striped. This will
        also remove template markup.
    comment_line_str
        Specify the string that comment lines will begin with.
    overwrite
        Overwrite output files if they exists.
    quiet
        Don't print status info while rendering.
    """
    console = rich.console.Console(stderr=True, quiet=quiet)
    econsole = rich.console.Console(stderr=True, quiet=quiet)

    font = "poinson"
    banner = art.text2art(f"CompuDoc", font=font)
    console.print(banner)
    console.print(f"version: {__version__}\n\n")

    if filetype is None:
        filetype = detect_filetype(input_file)
    if filetype is None and comment_line_str is None:
        console.print(f"Could not determine filetype for {input_file}")
        return 1

    if comment_line_str is None:
        comment_line_str = supported_filetypes[filetype]["comment line strings"][0]

    text_output = pathlib.Path(str(input_file) + text_suffix)
    code_output = pathlib.Path(str(input_file) + code_suffix)

    console.print(f"Detected filetype: {filetype}")
    console.print(rich.markup.escape(f"Comment string: {comment_line_str}"))
    console.print(
        f"Splitting '{input_file}' into text: '{text_output}' and code: '{code_output}'."
    )

    if not overwrite:
        output_exists = False
        for file in [text_output, code_output]:
            if file.exists():
                econsole.print(
                    f"[red]Error: {file} already exists. Give --overwrite to overwrite.[/red]"
                )
        if output_exists:
            econsole.print(
                f"[red]One or more output files exists and --overwrite was not given. Exiting.[/red]"
            )
            return 2

    input_text = input_file.read_text()
    doc = document.Document()
    doc.set_template_engine(Jinja2())
    doc.set_execution_engine(Python())
    doc.set_comment_block_parser(
        document.CodeBlockParser(comment_line_str=comment_line_str)
    )
    doc.parse(input_text)

    with text_output.open("w") as f:
        for i, block in doc.enumerate_text_blocks():
            if strip:
                text = doc.template_engine.strip_text(block.text)
            else:
                text = block.text
            f.write(text)

    with code_output.open("w") as f:
        f.write(doc.execution_engine.get_line_comment_str())
        f.write("{{{SETUP\}}}n")
        f.write(doc.template_engine.get_setup_code())
        for i, block in doc.enumerate_code_blocks():
            f.write(doc.execution_engine.get_line_comment_str())
            f.write("{{{BLOCK ")
            f.write(f"{i}")
            f.write("}}}\n")
            f.write(
                document.extract_code(
                    block.text, doc.comment_block_parser.comment_line_str
                )
            )

    return 0
